[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "pywhiz"
version = "0.2.0"
description = "A friendly, beginner-to-all Python helper package built for learning and hobby collaboration, prioritizing readable code and effortless utilities over pure commercial speed."
readme = "README.md"
requires-python = ">=3.8"
license = { text = "MIT" }
authors = [
    { name = "Diyon Daison" },
    { name = "Rethik Thilak" },
    { name = "Nihal Sam"}

]
keywords = ["utilities", "helpers", "shortcuts", "formatting", "easy", "pywhiz"]

[project.urls]
"Homepage" = "https://github.com/CrabbierDuke167/pywhiz"