[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "pywhiz"
version = "0.1.7"
description = "Fast, effortless, and friendly quality-of-life helper functions for Python developers."
readme = "README.md"
requires-python = ">=3.8"
license = { text = "MIT" }
authors = [
    { name = "Diyon Daison" },
    { name = "Rethik Thilak" },
    { name = "Nihal Sam"}

]
keywords = ["utilities", "helpers", "shortcuts", "formatting", "easy", "pywhiz"]

[project.urls]
"Homepage" = "https://github.com/yourusername/pywhiz"
